### ISSUE TITLE
Where to list the "with: version=.." statement?

### ISSUE THREAD

**Issue by Makki93** [errata-ai/vale-action#101]
As a YAML newbie, I didn't know where to add the "with" code block.
I now know it. I would have added it myself and opened a PR, but you don't allow it. In case you want to add it yourself, this is what I would have written in the README.md below the input section:

This input must be listed below the last `uses`-statement:

```yaml
jobs:
  vale:
    steps:
      - uses: errata-ai/vale-action@reviewdog
        with:
          version: latest
```
