### ISSUE TITLE
Why does reviewdog not fail the run?

### ISSUE THREAD

**Issue by karl-johan-grahn** [errata-ai/vale-action#116]
I'm running a spell check with:
```yaml
      - name: Spell check
        uses: errata-ai/vale-action@v2.0.1
        with:
          version: 3.0.5
          fail_on_error: true
          files: content
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
and vale reports three errors, however reviewdog does not fail the job even though `-fail-on-error=true`: https://github.com/stakater/secrets-docs/actions/runs/7562848951/job/20594324785
