### ISSUE TITLE
Warning when the action is installing asciidoctor

### ISSUE THREAD

**Issue by DanRoscigno** [errata-ai/vale-action#127]
I am not using asciidoctor, so I am not sure how important this is, but I am seeing this warning:

```
Installing collected packages: docutils
Successfully installed docutils-0.21.2
/usr/bin/gem install asciidoctor --user-install
WARNING:  You don't have /home/runner/.local/share/gem/ruby/3.0.0/bin in your PATH,
	  gem executables will not run.
```

Here is a fix. I will open a PR if you would like.

```yaml
name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
            ruby-version: '3.3'
      - run: echo "/home/runner/.local/share/gem/ruby/3.3.0/bin" >> $GITHUB_PATH
      - uses: errata-ai/vale-action@reviewdog
```
