### ISSUE TITLE
error: externally-managed-environment on ubuntu ubuntu-24.04

### ISSUE THREAD

**Issue by axel7083** [errata-ai/vale-action#128]
When using the latest version we are getting the following 

```
/usr/bin/pip install docutils
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.12/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
Error: Error: The process '/usr/bin/pip' failed with exit code 1
```

## workflow file

```yaml
name: Validate website language on pull request

on:
  pull_request:
    paths:
      - 'website/**'

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: website
          fail_on_error: false
```

**Comment by kayx23** [comment]
Same error on `ubuntu-24.04`. Following.

Current fix: reverting to `22.04`.

**Comment by zhangtbj** [comment]
> Same error on `ubuntu-24.04`. Following.
> 
> Current fix: reverting to `22.04`.

👍  It also works for me after rollback to the ubuntu `22.04`

**Comment by burgerdev** [comment]
This workaround allows staying on 24.04:

```yaml
name: reviewdog
on: [pull_request]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - run: |
          venv="$HOME/.local/share/venv"
          python3 -m venv "$venv"
          echo "$venv/bin" >> $GITHUB_PATH
      - uses: errata-ai/vale-action@reviewdog
```
