### ISSUE TITLE
Does vale support GitHub code suggestions?

### ISSUE THREAD

**Issue by mirnawong1** [errata-ai/vale-action#129]
I've been trying to implement the following in our [open-sourced docs repository](https://github.com/dbt-labs/docs.getdbt.com/tree/current) as a CI check:

- Vale linting to warn to enforce style guide configurations
- [reviewdog/action-suggester](https://github.com/reviewdog/action-suggester) to suggest the correct code based on the warnings to save the author a couple of steps. (E.g: if vale flagged that a word is repeated, I'd like the suggester to understand the output and warnings, and suggest the correct form: `The floor is is lava` should provide a GitHub code suggesting to remove the extra `is` and keep only 1 `is`.

I can get the vale linting working, however, I can't get the code suggester to work at all.  Can you confirm if vale itself can suggest code? I'm wondering if that's the disconnect.

Here's [my PR](https://github.com/dbt-labs/docs.getdbt.com/pull/5623) and github actions yaml configuration:

```
name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale: # Vale linting job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history so we can access all commits

    - name: Install Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-pr-review

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v44
      with:
        # Avoid using single or double quotes for multiline patterns
        files: |
           **.md

    - name: List all changed files markdown files
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-markdown-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done

    - name: Run Vale on changed files
      run: |
        for file in ${{ env.ALL_CHANGED_FILES }}; do
          echo "Running Vale on $file"
          vale --output=JSON $file > "vale_output_${file//\//_}.json"
          vale --output=edit $file > "vale_output_${file//\//_}_edit.md"
        done
        echo "Vale outputs:"
        ls -l
  
    - name: Suggest changes
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: reviewdog/action-suggester@v1
      with:
        tool_name: vale

 ```
