### ISSUE TITLE
Custom vale.ini location

### ISSUE THREAD

**Issue by paveldudka** [errata-ai/vale-action#134]
My docs are located not at the root of the repo and I want to keep all the vale config colocated with docs
However, I don't see a way to specify custom vale.ini location or change a working directory

**Comment by beritou** [comment]
I had the same issue and `vale_flags` was the solution that worked for me. 

```yml
      - name: "vale.sh spell check"
        uses: errata-ai/vale-action@reviewdog
        with:
          files: docs/src
          fail_on_error: true
          filter_mode: nofilter
          vale_flags: "--config=docs/.vale.ini"
```

Source: https://forem.julialang.org/kellertuer/improve-your-documentation-using-valesh-5587
