### ISSUE TITLE
asciidoctor not found

### ISSUE THREAD

**Issue by dunyakirkali** [errata-ai/vale-action#138]
I have the following vale config

```
StylesPath = .github/styles

MinAlertLevel = error

Packages = Google, proselint, write-good, Readability, AsciiDoc
Vocab = incremental_forgetting

[asciidoctor]
experimental = YES

[*]
BasedOnStyles = Vale, Google, proselint, write-good, Readability, AsciiDoc

Google.Quotes = NO
```

And this is the pipeline:
```
name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: source/
          fail_on_error: true

```

And I get the following error:

```
Running vale...
  /home/runner/vale --output=/home/runner/work/_actions/errata-ai/vale-action/reviewdog/lib/rdjsonl.tmpl .
  E100 [lintAdoc] Runtime error
  
  asciidoctor not found
  
  Execution stopped with code 1.
Error: Vale and reviewdog exited with status code: 2
```

Any clues to what I might be doing wrong?
