### ISSUE TITLE
v2.0.0 re-write

### ISSUE THREAD

**Issue by jdkato** [errata-ai/vale-action#65]
With the release of [v2.16.0](https://github.com/errata-ai/vale/releases/tag/v2.16.0) of Vale, the CLI now has built-in (and improved) support for the action's config-handling features. 

There's also been a number of changes to GitHub Actions since this one was created, so I figure it's a good time to think about a re-write:

- [x] Config handling should be managed in `.vale.ini`.
- [x] The version of Vale should be an action parameter.
- [x] Changed files logic should be offloaded to [reviewdog](https://github.com/reviewdog/reviewdog) (#32)
- [x] CLI options, such as `--glob`, should be supported (#37).
- [x] Better control of how/when the action fails (#26)
- [x] Support opt-in dependencies (#51)

maybe more ...

**Comment by glebbash** [comment]
@jdkato maybe it is also better to switch to vale 2.16 before the rewrite? So that packages will be available in vale-action a bit faster.

**Comment by jdkato** [comment]
It's already pretty close to being ready to use. Check out the [reviewdog](https://github.com/errata-ai/vale-action/tree/reviewdog) branch.

**Comment by glebbash** [comment]
New action works great 😍. Fulfills all our needs.

Thanks for improving this great tool! 🤝

**Comment by JulioPDX** [comment]
Testing this version has worked fantastic. One question, is there a way for vale to run on all md files in the repo vs just the ones that have been submitted with a PR? Good for repos that already exist with documentation vs new files in PR. Thank you

**Comment by jdkato** [comment]
You should be able to use a combination of [`github-check`](https://github.com/reviewdog/reviewdog#reporters) and [`nofilter`](https://github.com/reviewdog/reviewdog#filter-mode).

```yaml
lint:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: errata-ai/vale-action@reviewdog
        with:
          # only needed if you want push events too
          reporter: github-check
          filter_mode: nofilter
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
