### ISSUE TITLE
Failed executions in scheduled runs

### ISSUE THREAD

**Issue by fviolette** [errata-ai/vale-action#69]
When running vale in a cron job, the execution fails.
My example includes a custom runner which works in other contexts (push, pr).

```
on:
  schedule:
    - cron: "0 0 * * 1-5"

jobs:
  deploy:
    runs-on: ["nodejs-16"]
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        reporter: github-check
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

```
Installing Vale version 'latest' ...
/bin/tar xz --overwrite -C /github/home -f /runner/_work/_temp/1fb8e340-4ab8-436b-bc5c-87139bb85213
Installed version '2.17.0' into '/github/home/vale'.
/github/home/vale sync
Running vale with reviewdog 🐶 ...
  /github/home/vale --output=/lib/rdjsonl.tmpl .
  /bin/reviewdog -f=rdjsonl -name=vale -reporter=github-check -fail-on-error=false -filter-mode=added -level=error
  reviewdog: post failed for vale: failed to create check: POST https://api.github.com/repos///check-runs: 404 Not Found []
Error: reviewdog exited with status code: 1
```

See https://github.com/reviewdog/reviewdog/issues/832
