### ISSUE TITLE
Conclusion is success despite ERROR

### ISSUE THREAD

**Issue by pwalleni** [errata-ai/vale-action#81]
Hi! Given the following settings in .vale.ini:

```
Packages = Microsoft

StylesPath = .vale/styles

MinAlertLevel = suggestion

[*.md]
BasedOnStyles = Vale, Microsoft
```
And the GitHub workflow action:

```yaml
---                                                                             
name: Linting with Vale on pull request                                         
 on:                                                                             
   - pull_request_target                                                         
 jobs:                                                                           
   vale:                                                                         
     name: Linting with Vale                                                     
     runs-on: ubuntu-latest                                                      
     steps:                                                                      
       - name: Checkout                                                          
         uses: actions/checkout@v3.1.0                                           
       - name: Vale Linter                                                       
         uses: errata-ai/vale-action@reviewdog                                   
         with:                                                                   
           fail_on_error: true                                                   
         env:                                                                    
           GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} 
```

I fail to understand why the conclusion of running Vale with reviewdog is `conclusion=success`

```plaintext
Running vale with reviewdog 🐶 ...
  /github/home/vale --output=/lib/rdjsonl.tmpl .
  {"message": "[Microsoft.Adverbs] Consider removing 'very'.", "location": {"path": "docs/foo.md", "range": {"start": {"line": 1, "column": 5}}}, "severity": "WARNING"}
  {"message": "[Vale.Spelling] Did you really mean 'herrre'?", "location": {"path": "docs/foo.md", "range": {"start": {"line": 3, "column": 21}}}, "severity": "ERROR"}
  /bin/reviewdog -f=rdjsonl -name=vale -reporter=github-pr-check -fail-on-error=true -filter-mode=added -level=error
  2022/10/12 13:11:25 [vale] reported: https://github.com/volvo-cars/vale-test/runs/8846666662 (conclusion=success)
```

Any help debugging this issue is much appreciated 🙏🏼
