### ISSUE TITLE
Warning causes workflow to fail when `fail_on_error` is `true`

### ISSUE THREAD

**Issue by chadfawcett** [errata-ai/vale-action#84]
Based on [the docs](https://github.com/errata-ai/vale-action#fail_on_error-default-false), I would only expect the workflow to fail if there was an error. I'm seeing it fail when there is only a Warning. Is this the expected behaviour?

According to the [reviewdog docs](https://github.com/reviewdog/reviewdog#reporter-github-checks--reportergithub-pr-check), a Warning should result in a "neutral" GitHub Status.

**Comment by jdkato** [comment]
Warnings should indeed result in a `neutral` status -- see, for example, [this job](https://github.com/errata-ai/vale/actions/runs/3326278439/jobs/5499848774) with multiple warnings and a `neutral` status.

Can you share your `.vale.ini` and workflow config?

**Comment by chadfawcett** [comment]
Thanks for the response @jdkato. Here's my config setup

`.vale.ini`
```
MinAlertLevel = suggestion
StylesPath = .github/styles

[*.md]
BasedOnStyles = proselint, inclusive-language
proselint.Typography = NO
proselint.Cliches = NO
proselint.Very = NO
proselint.Cursing = NO
proselint.Currency = NO
proselint.CorporateSpeak = NO
proselint.Skunked = NO
proselint.DateSpacing = NO
proselint.DateCase = NO
proselint.Diacritical = NO
proselint.Hyperbole = NO
```

workflow
```yml
name: Vale Lint
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale
        uses: errata-ai/vale-action@e9cd17e2bb87ed772b939286b7b141d7ba64ed54
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          fail_on_error: true
```

Then the warning was for starting a paragraph with "but". Which is defined like so:
`.github/styles/proselint/But.yml`
```yml
extends: existence
message: "Do not start a paragraph with a 'but'."
level: warning
scope: paragraph
action:
  name: remove
tokens:
  - ^But
```
