### ISSUE TITLE
Action fails even if fail_on_error is false

### ISSUE THREAD

**Issue by jeromecambon** [errata-ai/vale-action#89]
I'm giving the vale-action the following parameters:
- fail_on_error: false
- vale_flags: "--no-exit"

However, I still have the action to fail if reviewdog fails:
```
/bin/reviewdog -f=rdjsonl -name=vale -reporter=github-pr-check -fail-on-error=false -filter-mode=added -level=info
...
Error: reviewdog: Too many results (annotations) in diff.
  You may miss some annotations due to GitHub limitation for annotation created by logging command.
  Please check GitHub Actions log console to see all results.
...
Error: reviewdog exited with status code: 1
```
Whatever reviewdog is returning, Vale action should not fail if fail_on_error is false.

**Comment by jeromecambon** [comment]
Any workaround for this? Thanks!

**Comment by jeromecambon** [comment]
I have a fix for this, but don't have the rights to create a PR.

**Comment by michelle-purcell** [comment]
@jeromecambon - Thank you for raising this issue. I am also reproducing this problem too in a GitHub action.

The issue occurs regardless of whether I use `actions/checkout@v3` or `uses: actions/checkout@v2`.

Here's an extract of the YAML configuration that reproduces the issue:
````

jobs:
  vale:
    name: Linting with Vale
    runs-on: ubuntu-latest
    permissions:
      actions: read
      checks: read
      contents: read
      pull-requests: read
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Vale Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: false
          vale_flags: "--no-exit --config=docs/.vale/vale.ini"
          filter_mode: diff_context
          files: docs/src/main/asciidoc/
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

````

[jdkato](https://github.com/jdkato) - Some context: We are implementing Vale as a pilot test in one project, and during the initial introduction of the Vale inter to the git workflow, we would like to ensure that a PR is not blocked, regardless of whether there are errors, warnings, or suggestions.  Is there a  workaround for this issue to prevent the build failure?  Thank you.
