### ISSUE TITLE
Any way to run Vale only on changed files in a PR (github workflow)?

### ISSUE THREAD

**Issue by kayx23** [errata-ai/vale-action#95]
Hello! I'd like to only run Vale on changed files in a PR (based on all commits in the PR). My github workflow config file is as follows:

```
name: reviewdog
on: [pull_request]

jobs:
  vale-linter:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get changed files in the PR
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/base
          git diff --name-only --diff-filter=d $(git merge-base HEAD origin/base)..HEAD > changed_files_in_PR.txt
      - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: $(cat changed_files_in_PR.txt)
          reporter: github-check
          fail_on_error: true
```

Getting the warning in the stout: `Warning: User-specified path ($(cat changed_files_in_PR.txt)) is invalid; falling back to 'all'.`

Any help would be highly appreciated!

**Comment by cymruu** [comment]
I think what's happening is that GitHub is treating the input files as a string literal, which means the command isn't being executed. To fix this, you need to actually execute `cat` on that file and save the result into a variable 

```
- name: Set variables
  run: |
    CHANGED_FILES=$(cat changed_files_in_PR.txt)
    echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV
```
and then use created environmental variable in last step

```
 - uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          files: ${{env.CHANGED_FILES}}
          reporter: github-check
          fail_on_error: true
```

**Comment by kayx23** [comment]
@cymruu Thanks for the help! I tried your suggestion and got rid of the warning but vale is still running on all files, instead of just the changed files... 

![image](https://user-images.githubusercontent.com/39619599/229422997-043a296b-2632-4659-bfd2-db887eaf6947.png)

The job is [here](https://github.com/api7/docs/actions/runs/4593351626/jobs/8111187749?pr=119)

Any idea?

**Comment by cymruu** [comment]
@kayx23 I tried to debug it, and I think it's not working because the git diff command isn't returning any changed files. This causes linting of all files in the repository.

Maybe using the action debug mode would help you more
https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging

**Comment by kayx23** [comment]
Will do. Thanks again for the help!

update: yes that `git diff` command was completely off

**Comment by kayx23** [comment]
This worked for me: 

```
name: reviewdog
on: [pull_request]

jobs:
  run-vale-on-changed-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: get-changed-files
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'csv'
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: vale
        uses: errata-ai/vale-action@reviewdog
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          separator: ","
          files: ${{ steps.files.outputs.added_modified }}
          reporter: github-check
          fail_on_error: true
```

Also I just realized most of that 1-min CI wait time for Vale was due to building reviewdog... Running vale on all files only take about 4s out of the minute, so this optimization doesn't mean much (yes, I seriously just noticed, gasp). Nonetheless it was fun playing around and figure out how to make this work... 

For my specific use case I'll just add some github action condition to only build/run vale if and only if PR changed files include markdown files.
