### ISSUE TITLE
exclude/ignore paths in GH Action

### ISSUE THREAD

**Issue by sudhanshu456** [errata-ai/vale-action#96]
I was looking for a way to exclude files and stumbled upon this issue on GitHub: https://github.com/errata-ai/vale/issues/254. I noticed that Vale CLI has a glob option, so I tried to find the same option in the GitHub action, but I couldn't locate it. Can you please advise me on how to proceed?

Is there an option that I may have overlooked in the action parameters? If not, would it be possible to add this feature?

**Comment by spier** [comment]
@sudhanshu456 according to these [docs](https://github.com/marketplace/actions/vale-linter#vale_flags-default-) you can use the `vale_flags` property of the GitHub Action for this purpose. e.g.

```
    - name: Vale Linting
      uses: errata-ai/vale-action@reviewdog
      with:
        vale_flags: "--glob=*.md"
```
